-- ============================================================
--  casev_db — Import nella tabella: utenti
--  Password temporanea: 12345678  |  auth_type: ldap
--  Righe: 131
-- ============================================================

USE casev_db;

INSERT INTO utenti (
    username, password_hash, nome, cognome,
    email, ruolo, categoria, grado,
    sede_assegnazione, matricola, auth_type, attivo
) VALUES
('giannelli.daniele', '$2b$12$5nC.xSdDNOOGUEv0XnbweOR7o.DMXSq2HiphBmk3Oi2yTcuSj4SVq', 'DANIELE', 'GIANNELLI', 'daniele.giannelli@mit.gov.it', 'efv', 'Piloti', 'C.V.(CP) Pil', 'MARICOGECAP', NULL, 'ldap', 1),
('migli.stefano', '$2b$12$5nC.xSdDNOOGUEv0XnbweOR7o.DMXSq2HiphBmk3Oi2yTcuSj4SVq', 'STEFANO', 'MIGLI', 'stefano.migli@mit.gov.it', 'efv', 'Tecnici di volo', 'C.F.(CP) Tc-Eli', 'MARICOGECAP', NULL, 'ldap', 1),
('coco.saverio', '$2b$12$5nC.xSdDNOOGUEv0XnbweOR7o.DMXSq2HiphBmk3Oi2yTcuSj4SVq', 'SAVERIO', 'COCO', 'saverio.coco@mit.gov.it', 'efv', 'Piloti', 'C.C. (CP) Pil', 'MARICOGECAP', NULL, 'ldap', 1),
('d^ambrogio.paolo', '$2b$12$5nC.xSdDNOOGUEv0XnbweOR7o.DMXSq2HiphBmk3Oi2yTcuSj4SVq', 'PAOLO', 'D^AMBROGIO', 'paolo.d^ambrogio@mit.gov.it', 'efv', 'Tecnici di volo', '1° M.llo Np-Tc-aer', 'MARICOGECAP', NULL, 'ldap', 1),
('dinardo.marco', '$2b$12$5nC.xSdDNOOGUEv0XnbweOR7o.DMXSq2HiphBmk3Oi2yTcuSj4SVq', 'MARCO', 'DI NARDO', 'marco.dinardo@mit.gov.it', 'efv', 'Piloti', 'C.F.(CP) Pil', 'NAAF', NULL, 'ldap', 1),
('mazzei.massimo', '$2b$12$5nC.xSdDNOOGUEv0XnbweOR7o.DMXSq2HiphBmk3Oi2yTcuSj4SVq', 'MASSIMO', 'MAZZEI', 'massimo.mazzei@mit.gov.it', 'efv', 'Tecnici di volo', 'C.F. (CP) Tc-Eli', 'NAAF', NULL, 'ldap', 1),
('natale.luigi', '$2b$12$5nC.xSdDNOOGUEv0XnbweOR7o.DMXSq2HiphBmk3Oi2yTcuSj4SVq', 'LUIGI', 'NATALE', 'luigi.natale@mit.gov.it', 'efv', 'Operatori di volo', 'Lgt Np/Ov', 'NAAF', NULL, 'ldap', 1),
('liardo.sergio', '$2b$12$5nC.xSdDNOOGUEv0XnbweOR7o.DMXSq2HiphBmk3Oi2yTcuSj4SVq', 'SERGIO', 'LIARDO', 'sergio.liardo@mit.gov.it', 'efv', 'Piloti', 'CA (CP) Pil', 'MARICOGECAP', NULL, 'ldap', 1),
('stefanizzi.lorenzo', '$2b$12$5nC.xSdDNOOGUEv0XnbweOR7o.DMXSq2HiphBmk3Oi2yTcuSj4SVq', 'LORENZO', 'STEFANIZZI', 'lorenzo.stefanizzi@mit.gov.it', 'efv', 'Tecnici di volo', 'Sc  Np Ms-Saer', 'SAGUARCOST PESCARA', NULL, 'ldap', 1),
('amitrano.luigi', '$2b$12$5nC.xSdDNOOGUEv0XnbweOR7o.DMXSq2HiphBmk3Oi2yTcuSj4SVq', 'LUIGI', 'AMITRANO', 'luigi.amitrano@mit.gov.it', 'efv', 'Tecnici di volo', 'C.V.(CP) Tc-eli', 'MARICOGECAP', NULL, 'ldap', 1),
('baccari.simone', '$2b$12$5nC.xSdDNOOGUEv0XnbweOR7o.DMXSq2HiphBmk3Oi2yTcuSj4SVq', 'SIMONE', 'BACCARI', 'simone.baccari@mit.gov.it', 'efv', 'Tecnici di volo', 'C.F. (CP) Tc/Aer', 'SAGUARCOST CATANIA', NULL, 'ldap', 1),
('prencipe.antonio', '$2b$12$5nC.xSdDNOOGUEv0XnbweOR7o.DMXSq2HiphBmk3Oi2yTcuSj4SVq', 'ANTONIO', 'PRENCIPE', 'antonio.prencipe@mit.gov.it', 'efv', 'Piloti', 'C.F. (CP) Pil', 'SAGUARCOST PESCARA', NULL, 'ldap', 1),
('cambria.giuseppe', '$2b$12$5nC.xSdDNOOGUEv0XnbweOR7o.DMXSq2HiphBmk3Oi2yTcuSj4SVq', 'GIUSEPPE', 'CAMBRIA', 'giuseppe.cambria@mit.gov.it', 'efv', 'Operatori di volo', '2° Capo Np Ov', 'SAGUARCOST CATANIA', NULL, 'ldap', 1),
('savini.giovanni', '$2b$12$5nC.xSdDNOOGUEv0XnbweOR7o.DMXSq2HiphBmk3Oi2yTcuSj4SVq', 'GIOVANNI', 'SAVINI', 'giovanni.savini@mit.gov.it', 'efv', 'Piloti', 'G.M.(CP) Pil', 'SAGUARCOST CATANIA', NULL, 'ldap', 1),
('cassanelli.max', '$2b$12$5nC.xSdDNOOGUEv0XnbweOR7o.DMXSq2HiphBmk3Oi2yTcuSj4SVq', 'MAX', 'CASSANELLI', 'max.cassanelli@mit.gov.it', 'efv', 'Piloti', 'G.M.(CP) Pil', 'SAGUARCOST PESCARA', NULL, 'ldap', 1),
('ghidara.marco', '$2b$12$5nC.xSdDNOOGUEv0XnbweOR7o.DMXSq2HiphBmk3Oi2yTcuSj4SVq', 'MARCO', 'GHIDARA', 'marco.ghidara@mit.gov.it', 'efv', 'Operatori di volo', 'SC Np Ov', 'SAGUARCOST PESCARA', NULL, 'ldap', 1),
('scire.giovanni', '$2b$12$5nC.xSdDNOOGUEv0XnbweOR7o.DMXSq2HiphBmk3Oi2yTcuSj4SVq', 'GIOVANNI', 'SCIRE', 'giovanni.scire@mit.gov.it', 'efv', 'Piloti', 'G.M.(CP) Pil', 'SAGUARCOST CATANIA', NULL, 'ldap', 1),
('veca.giacomo', '$2b$12$5nC.xSdDNOOGUEv0XnbweOR7o.DMXSq2HiphBmk3Oi2yTcuSj4SVq', 'GIACOMO', 'VECA', 'giacomo.veca@mit.gov.it', 'efv', 'Operatori di volo', 'Lgt Np Ov', 'SAGUARCOST CATANIA', NULL, 'ldap', 1),
('deffereria.riccardo', '$2b$12$5nC.xSdDNOOGUEv0XnbweOR7o.DMXSq2HiphBmk3Oi2yTcuSj4SVq', 'RICCARDO', 'DEFFERERIA', 'riccardo.deffereria@mit.gov.it', 'efv', 'Piloti', 'C.F. (CP) Pil', 'SAGUARCOST CATANIA', NULL, 'ldap', 1),
('andrisani.francesco', '$2b$12$5nC.xSdDNOOGUEv0XnbweOR7o.DMXSq2HiphBmk3Oi2yTcuSj4SVq', 'FRANCESCO', 'ANDRISANI', 'francesco.andrisani@mit.gov.it', 'efv', 'Piloti', 'C.F.(CP) Ov', 'MARICOGECAP', NULL, 'ldap', 1),
('pianelli.boris', '$2b$12$5nC.xSdDNOOGUEv0XnbweOR7o.DMXSq2HiphBmk3Oi2yTcuSj4SVq', 'BORIS', 'PIANELLI', 'boris.pianelli@mit.gov.it', 'efv', 'Piloti', 'C.F. (CP) Pil', 'SAGUARCOST CATANIA', NULL, 'ldap', 1),
('bruno.massimiliano', '$2b$12$5nC.xSdDNOOGUEv0XnbweOR7o.DMXSq2HiphBmk3Oi2yTcuSj4SVq', 'MASSIMILIANO', 'BRUNO', 'massimiliano.bruno@mit.gov.it', 'efv', 'Piloti', 'C.F. (CP) Pil', 'SAGUARCOST PESCARA', NULL, 'ldap', 1),
('biasco.giuseppe', '$2b$12$5nC.xSdDNOOGUEv0XnbweOR7o.DMXSq2HiphBmk3Oi2yTcuSj4SVq', 'GIUSEPPE', 'BIASCO', 'giuseppe.biasco@mit.gov.it', 'efv', 'Piloti', 'C.F. (CP) Pil', 'SAGUARCOST PESCARA', NULL, 'ldap', 1),
('colarossi.luca', '$2b$12$5nC.xSdDNOOGUEv0XnbweOR7o.DMXSq2HiphBmk3Oi2yTcuSj4SVq', 'LUCA', 'COLAROSSI', 'luca.colarossi@mit.gov.it', 'efv', 'Piloti', 'T.V. (CP) Pil.', 'SAGUARCOST PESCARA', NULL, 'ldap', 1),
('cavallo.fioravante', '$2b$12$5nC.xSdDNOOGUEv0XnbweOR7o.DMXSq2HiphBmk3Oi2yTcuSj4SVq', 'FIORAVANTE', 'CAVALLO', 'fioravante.cavallo@mit.gov.it', 'efv', 'Tecnici di volo', '1° Lgt Np Ms-saer', 'SAGUARCOST PESCARA', NULL, 'ldap', 1),
('guardascione.salvatore', '$2b$12$5nC.xSdDNOOGUEv0XnbweOR7o.DMXSq2HiphBmk3Oi2yTcuSj4SVq', 'SALVATORE', 'GUARDASCIONE', 'salvatore.guardascione@mit.gov.it', 'efv', 'Tecnici di volo', 'Lgt  Np Mo-taer', 'SAGUARCOST PESCARA', NULL, 'ldap', 1),
('digirolamo.alessandro', '$2b$12$5nC.xSdDNOOGUEv0XnbweOR7o.DMXSq2HiphBmk3Oi2yTcuSj4SVq', 'ALESSANDRO', 'DI GIROLAMO', 'alessandro.digirolamo@mit.gov.it', 'efv', 'Operatori di volo', 'Lgt Np Ov', 'SAGUARCOST PESCARA', NULL, 'ldap', 1),
('pisano.tommaso', '$2b$12$5nC.xSdDNOOGUEv0XnbweOR7o.DMXSq2HiphBmk3Oi2yTcuSj4SVq', 'TOMMASO', 'PISANO', 'tommaso.pisano@mit.gov.it', 'efv', 'Operatori di volo', '1° M.llo Np-OV', 'SAGUARCOST PESCARA', NULL, 'ldap', 1),
('d^andrea.salvatore', '$2b$12$5nC.xSdDNOOGUEv0XnbweOR7o.DMXSq2HiphBmk3Oi2yTcuSj4SVq', 'SALVATORE', 'D^ANDREA', 'salvatore.d^andrea@mit.gov.it', 'efv', 'Operatori di volo', 'Lgt Np Ov', 'SAGUARCOST PESCARA', NULL, 'ldap', 1),
('lasaponara.francesco', '$2b$12$5nC.xSdDNOOGUEv0XnbweOR7o.DMXSq2HiphBmk3Oi2yTcuSj4SVq', 'FRANCESCO', 'LASAPONARA', 'francesco.lasaponara@mit.gov.it', 'efv', 'Tecnici di volo', 'Lgt Np Ms-saer', 'SAGUARCOST PESCARA', NULL, 'ldap', 1),
('maiolo.giuseppe', '$2b$12$5nC.xSdDNOOGUEv0XnbweOR7o.DMXSq2HiphBmk3Oi2yTcuSj4SVq', 'GIUSEPPE', 'MAIOLO', 'giuseppe.maiolo@mit.gov.it', 'efv', 'Tecnici di volo', 'Lgt Np Mo-taer', 'SAGUARCOST PESCARA', NULL, 'ldap', 1),
('demarco.sandro', '$2b$12$5nC.xSdDNOOGUEv0XnbweOR7o.DMXSq2HiphBmk3Oi2yTcuSj4SVq', 'SANDRO', 'DE MARCO', 'sandro.demarco@mit.gov.it', 'efv', 'Tecnici di volo', 'Lgt Np Mo-taer', 'SAGUARCOST PESCARA', NULL, 'ldap', 1),
('arcadio.domenico', '$2b$12$5nC.xSdDNOOGUEv0XnbweOR7o.DMXSq2HiphBmk3Oi2yTcuSj4SVq', 'DOMENICO', 'ARCADIO', 'domenico.arcadio@mit.gov.it', 'efv', 'Tecnici di volo', 'Lgt Np-taer', 'SAGUARCOST PESCARA', NULL, 'ldap', 1),
('bosso.adriano', '$2b$12$5nC.xSdDNOOGUEv0XnbweOR7o.DMXSq2HiphBmk3Oi2yTcuSj4SVq', 'ADRIANO', 'BOSSO', 'adriano.bosso@mit.gov.it', 'efv', 'Tecnici di volo', 'Lgt  Np-taer', 'SAGUARCOST PESCARA', NULL, 'ldap', 1),
('cutrignelli.leonardo', '$2b$12$5nC.xSdDNOOGUEv0XnbweOR7o.DMXSq2HiphBmk3Oi2yTcuSj4SVq', 'LEONARDO', 'CUTRIGNELLI', 'leonardo.cutrignelli@mit.gov.it', 'efv', 'Operatori di volo', 'Lgt Np Ov', 'SAGUARCOST PESCARA', NULL, 'ldap', 1),
('manigrasso.antonio', '$2b$12$5nC.xSdDNOOGUEv0XnbweOR7o.DMXSq2HiphBmk3Oi2yTcuSj4SVq', 'ANTONIO', 'MANIGRASSO', 'antonio.manigrasso@mit.gov.it', 'efv', 'Tecnici di volo', 'Lgt Np Mo-taer', 'SAGUARCOST PESCARA', NULL, 'ldap', 1),
('iacullo.salvatore', '$2b$12$5nC.xSdDNOOGUEv0XnbweOR7o.DMXSq2HiphBmk3Oi2yTcuSj4SVq', 'SALVATORE', 'IACULLO', 'salvatore.iacullo@mit.gov.it', 'efv', 'Operatori di volo', 'Lgt Np OV', 'SAGUARCOST PESCARA', NULL, 'ldap', 1),
('cacace.michele', '$2b$12$5nC.xSdDNOOGUEv0XnbweOR7o.DMXSq2HiphBmk3Oi2yTcuSj4SVq', 'MICHELE', 'CACACE', 'michele.cacace@mit.gov.it', 'efv', 'Tecnici di volo', 'Lgt Np Ms-saer', 'SAGUARCOST PESCARA', NULL, 'ldap', 1),
('boccuni.francesco', '$2b$12$5nC.xSdDNOOGUEv0XnbweOR7o.DMXSq2HiphBmk3Oi2yTcuSj4SVq', 'FRANCESCO', 'BOCCUNI', 'francesco.boccuni@mit.gov.it', 'efv', 'Tecnici di volo', 'Capo 2^ Np Tc-Taer', 'SAGUARCOST PESCARA', NULL, 'ldap', 1),
('monaco.enrico', '$2b$12$5nC.xSdDNOOGUEv0XnbweOR7o.DMXSq2HiphBmk3Oi2yTcuSj4SVq', 'ENRICO', 'MONACO', 'enrico.monaco@mit.gov.it', 'efv', 'Operatori di volo', '2°C Sc Np-OV', 'SAGUARCOST PESCARA', NULL, 'ldap', 1),
('genovesed..davide', '$2b$12$5nC.xSdDNOOGUEv0XnbweOR7o.DMXSq2HiphBmk3Oi2yTcuSj4SVq', 'DAVIDE', 'GENOVESE D.', 'davide.genovesed.@mit.gov.it', 'efv', 'Operatori di volo', 'Sc.2ª cl Np-OV', 'SAGUARCOST PESCARA', NULL, 'ldap', 1),
('lillo.giancarlo', '$2b$12$5nC.xSdDNOOGUEv0XnbweOR7o.DMXSq2HiphBmk3Oi2yTcuSj4SVq', 'GIANCARLO', 'LILLO', 'giancarlo.lillo@mit.gov.it', 'efv', 'Operatori di volo', 'Sgt  Np-OV', 'SAGUARCOST PESCARA', NULL, 'ldap', 1),
('basile.francesco', '$2b$12$5nC.xSdDNOOGUEv0XnbweOR7o.DMXSq2HiphBmk3Oi2yTcuSj4SVq', 'FRANCESCO', 'BASILE', 'francesco.basile@mit.gov.it', 'efv', 'Tecnici di volo', 'C.F. (CP) Tc-Eli', 'SAGUARCOST PESCARA', NULL, 'ldap', 1),
('oliva.graziano', '$2b$12$5nC.xSdDNOOGUEv0XnbweOR7o.DMXSq2HiphBmk3Oi2yTcuSj4SVq', 'GRAZIANO', 'OLIVA', 'graziano.oliva@mit.gov.it', 'efv', 'Tecnici di volo', 'Lgt  Np Tc-taer', 'SAGUARCOST PESCARA', NULL, 'ldap', 1),
('tavaglione.giuseppe', '$2b$12$5nC.xSdDNOOGUEv0XnbweOR7o.DMXSq2HiphBmk3Oi2yTcuSj4SVq', 'GIUSEPPE', 'TAVAGLIONE', 'giuseppe.tavaglione@mit.gov.it', 'efv', 'Piloti', 'C.C.(CP) Pil', 'SAGUARCOST PESCARA', NULL, 'ldap', 1),
('demasi.luca', '$2b$12$5nC.xSdDNOOGUEv0XnbweOR7o.DMXSq2HiphBmk3Oi2yTcuSj4SVq', 'LUCA', 'DE MASI', 'luca.demasi@mit.gov.it', 'efv', 'Piloti', 'C.C.(CP) Pil', 'SAGUARCOST PESCARA', NULL, 'ldap', 1),
('infante.arcangelo', '$2b$12$5nC.xSdDNOOGUEv0XnbweOR7o.DMXSq2HiphBmk3Oi2yTcuSj4SVq', 'ARCANGELO', 'INFANTE', 'arcangelo.infante@mit.gov.it', 'efv', 'Tecnici di volo', 'Sc 1^ Cl Np Ms-Saer', 'SAGUARCOST PESCARA', NULL, 'ldap', 1),
('vitariello.giuseppe', '$2b$12$5nC.xSdDNOOGUEv0XnbweOR7o.DMXSq2HiphBmk3Oi2yTcuSj4SVq', 'GIUSEPPE', 'VITARIELLO', 'giuseppe.vitariello@mit.gov.it', 'efv', 'Tecnici di volo', '2° Capo Np Ms-Saer', 'SAGUARCOST PESCARA', NULL, 'ldap', 1),
('pandolfo.vincenzo', '$2b$12$5nC.xSdDNOOGUEv0XnbweOR7o.DMXSq2HiphBmk3Oi2yTcuSj4SVq', 'VINCENZO', 'PANDOLFO', 'vincenzo.pandolfo@mit.gov.it', 'efv', 'Operatori di volo', 'SC Np Ov', 'SAGUARCOST PESCARA', NULL, 'ldap', 1),
('toscano.francesco', '$2b$12$5nC.xSdDNOOGUEv0XnbweOR7o.DMXSq2HiphBmk3Oi2yTcuSj4SVq', 'FRANCESCO', 'TOSCANO', 'francesco.toscano@mit.gov.it', 'efv', 'Operatori di volo', 'SC Np Ov', 'SAGUARCOST PESCARA', NULL, 'ldap', 1),
('anatilopan.massimiliano', '$2b$12$5nC.xSdDNOOGUEv0XnbweOR7o.DMXSq2HiphBmk3Oi2yTcuSj4SVq', 'MASSIMILIANO', 'ANATILOPAN', 'massimiliano.anatilopan@mit.gov.it', 'efv', 'Tecnici di volo', 'Lgt Np Tc-Taer', 'SAGUARCOST PESCARA', NULL, 'ldap', 1),
('cucci.andrea', '$2b$12$5nC.xSdDNOOGUEv0XnbweOR7o.DMXSq2HiphBmk3Oi2yTcuSj4SVq', 'ANDREA', 'CUCCI', 'andrea.cucci@mit.gov.it', 'efv', 'Operatori di volo', 'SC Np Ov', 'SAGUARCOST PESCARA', NULL, 'ldap', 1),
('bissacco.stefano', '$2b$12$5nC.xSdDNOOGUEv0XnbweOR7o.DMXSq2HiphBmk3Oi2yTcuSj4SVq', 'STEFANO', 'BISSACCO', 'stefano.bissacco@mit.gov.it', 'efv', 'Tecnici di volo', 'C.C.(CP) Tc-aer', 'SAGUARCOST PESCARA', NULL, 'ldap', 1),
('turini.giovanni', '$2b$12$5nC.xSdDNOOGUEv0XnbweOR7o.DMXSq2HiphBmk3Oi2yTcuSj4SVq', 'GIOVANNI', 'TURINI', 'giovanni.turini@mit.gov.it', 'efv', 'Piloti', 'C.C.(CP) Pil', 'SAGUARCOST PESCARA', NULL, 'ldap', 1),
('chirico.luigi', '$2b$12$5nC.xSdDNOOGUEv0XnbweOR7o.DMXSq2HiphBmk3Oi2yTcuSj4SVq', 'LUIGI', 'CHIRICO', 'luigi.chirico@mit.gov.it', 'efv', 'Operatori di volo', 'SC Np Ov', 'SAGUARCOST PESCARA', NULL, 'ldap', 1),
('falco.francesco', '$2b$12$5nC.xSdDNOOGUEv0XnbweOR7o.DMXSq2HiphBmk3Oi2yTcuSj4SVq', 'FRANCESCO', 'FALCO', 'francesco.falco@mit.gov.it', 'efv', 'Piloti', 'T.V.(CP) Pil', 'SAGUARCOST CATANIA', NULL, 'ldap', 1),
('spagnolo.roberto', '$2b$12$5nC.xSdDNOOGUEv0XnbweOR7o.DMXSq2HiphBmk3Oi2yTcuSj4SVq', 'ROBERTO', 'SPAGNOLO', 'roberto.spagnolo@mit.gov.it', 'efv', 'Tecnici di volo', '1° Lgt Np Taer', 'SAGUARCOST PESCARA', NULL, 'ldap', 1),
('mariano.andrea', '$2b$12$5nC.xSdDNOOGUEv0XnbweOR7o.DMXSq2HiphBmk3Oi2yTcuSj4SVq', 'ANDREA', 'MARIANO', 'andrea.mariano@mit.gov.it', 'efv', 'Tecnici di volo', 'Sc 2^ Cl Np Ms-Saer', 'SAGUARCOST PESCARA', NULL, 'ldap', 1),
('martini.fabio', '$2b$12$5nC.xSdDNOOGUEv0XnbweOR7o.DMXSq2HiphBmk3Oi2yTcuSj4SVq', 'FABIO', 'MARTINI', 'fabio.martini@mit.gov.it', 'efv', 'Piloti', 'C.F. (CP) Pil', 'SAGUARCOST CATANIA', NULL, 'ldap', 1),
('pacci.giacomo', '$2b$12$5nC.xSdDNOOGUEv0XnbweOR7o.DMXSq2HiphBmk3Oi2yTcuSj4SVq', 'GIACOMO', 'PACCI', 'giacomo.pacci@mit.gov.it', 'efv', 'Piloti', 'C.F. (CP) Pil', 'SAGUARCOST CATANIA', NULL, 'ldap', 1),
('landi.rocco', '$2b$12$5nC.xSdDNOOGUEv0XnbweOR7o.DMXSq2HiphBmk3Oi2yTcuSj4SVq', 'ROCCO', 'LANDI', 'rocco.landi@mit.gov.it', 'efv', 'Piloti', 'C.C.(CP) Pil', 'SAGUARCOST CATANIA', NULL, 'ldap', 1),
('panebianco.alfio', '$2b$12$5nC.xSdDNOOGUEv0XnbweOR7o.DMXSq2HiphBmk3Oi2yTcuSj4SVq', 'ALFIO', 'PANEBIANCO', 'alfio.panebianco@mit.gov.it', 'efv', 'Operatori di volo', 'Sc.2ª cl Np-OV', 'SAGUARCOST CATANIA', NULL, 'ldap', 1),
('viola.vincenzo', '$2b$12$5nC.xSdDNOOGUEv0XnbweOR7o.DMXSq2HiphBmk3Oi2yTcuSj4SVq', 'VINCENZO', 'VIOLA', 'vincenzo.viola@mit.gov.it', 'efv', 'Piloti', 'T.V.(CP) Pil', 'SAGUARCOST CATANIA', NULL, 'ldap', 1),
('colombo.fabrizio', '$2b$12$5nC.xSdDNOOGUEv0XnbweOR7o.DMXSq2HiphBmk3Oi2yTcuSj4SVq', 'FABRIZIO', 'COLOMBO', 'fabrizio.colombo@mit.gov.it', 'efv', 'Piloti', 'C.C.(CP) Pil', 'SAGUARCOST CATANIA', NULL, 'ldap', 1),
('santone.alessandro', '$2b$12$5nC.xSdDNOOGUEv0XnbweOR7o.DMXSq2HiphBmk3Oi2yTcuSj4SVq', 'ALESSANDRO', 'SANTONE', 'alessandro.santone@mit.gov.it', 'efv', 'Piloti', 'T.V.(CP) Pil', 'SAGUARCOST CATANIA', NULL, 'ldap', 1),
('calosso.giorgio', '$2b$12$5nC.xSdDNOOGUEv0XnbweOR7o.DMXSq2HiphBmk3Oi2yTcuSj4SVq', 'GIORGIO', 'CALOSSO', 'giorgio.calosso@mit.gov.it', 'efv', 'Piloti', 'T.V.(CP) Pil', 'SAGUARCOST CATANIA', NULL, 'ldap', 1),
('oliviero.alessandro', '$2b$12$5nC.xSdDNOOGUEv0XnbweOR7o.DMXSq2HiphBmk3Oi2yTcuSj4SVq', 'ALESSANDRO', 'OLIVIERO', 'alessandro.oliviero@mit.gov.it', 'efv', 'Piloti', 'T.V.(CP) Pil', 'SAGUARCOST CATANIA', NULL, 'ldap', 1),
('livolsi.angelo', '$2b$12$5nC.xSdDNOOGUEv0XnbweOR7o.DMXSq2HiphBmk3Oi2yTcuSj4SVq', 'ANGELO', 'LIVOLSI', 'angelo.livolsi@mit.gov.it', 'efv', 'Operatori di volo', 'Lgt Np Ov', 'SAGUARCOST CATANIA', NULL, 'ldap', 1),
('petralia.marco', '$2b$12$5nC.xSdDNOOGUEv0XnbweOR7o.DMXSq2HiphBmk3Oi2yTcuSj4SVq', 'MARCO', 'PETRALIA', 'marco.petralia@mit.gov.it', 'efv', 'Operatori di volo', '2° Capo Np Ov', 'SAGUARCOST CATANIA', NULL, 'ldap', 1),
('spadola.giorgio', '$2b$12$5nC.xSdDNOOGUEv0XnbweOR7o.DMXSq2HiphBmk3Oi2yTcuSj4SVq', 'GIORGIO', 'SPADOLA', 'giorgio.spadola@mit.gov.it', 'efv', 'Operatori di volo', 'SC Np Ov', 'SAGUARCOST CATANIA', NULL, 'ldap', 1),
('genovesea..andrea', '$2b$12$5nC.xSdDNOOGUEv0XnbweOR7o.DMXSq2HiphBmk3Oi2yTcuSj4SVq', 'ANDREA', 'GENOVESE A.', 'andrea.genovesea.@mit.gov.it', 'efv', 'Operatori di volo', '2° Capo Np Ov', 'SAGUARCOST CATANIA', NULL, 'ldap', 1),
('fornito.salvatore', '$2b$12$5nC.xSdDNOOGUEv0XnbweOR7o.DMXSq2HiphBmk3Oi2yTcuSj4SVq', 'SALVATORE', 'FORNITO', 'salvatore.fornito@mit.gov.it', 'efv', 'Tecnici di volo', '2° Capo Sc Qc Np Ms-Saer', 'SAGUARCOST CATANIA', NULL, 'ldap', 1),
('leocata.alessio', '$2b$12$5nC.xSdDNOOGUEv0XnbweOR7o.DMXSq2HiphBmk3Oi2yTcuSj4SVq', 'ALESSIO', 'LEOCATA', 'alessio.leocata@mit.gov.it', 'efv', 'Operatori di volo', '2° Capo Np Ov', 'SAGUARCOST CATANIA', NULL, 'ldap', 1),
('scavera.francesco', '$2b$12$5nC.xSdDNOOGUEv0XnbweOR7o.DMXSq2HiphBmk3Oi2yTcuSj4SVq', 'FRANCESCO', 'SCAVERA', 'francesco.scavera@mit.gov.it', 'efv', 'Operatori di volo', '2°CapoSC Qc  Np Ov', 'SAGUARCOST CATANIA', NULL, 'ldap', 1),
('toscanoc..carmelo', '$2b$12$5nC.xSdDNOOGUEv0XnbweOR7o.DMXSq2HiphBmk3Oi2yTcuSj4SVq', 'CARMELO', 'TOSCANO C.', 'carmelo.toscanoc.@mit.gov.it', 'efv', 'Operatori di volo', 'Lgt Np Ov', 'SAGUARCOST CATANIA', NULL, 'ldap', 1),
('muscara.mario', '$2b$12$5nC.xSdDNOOGUEv0XnbweOR7o.DMXSq2HiphBmk3Oi2yTcuSj4SVq', 'MARIO', 'MUSCARA', 'mario.muscara@mit.gov.it', 'efv', 'Tecnici di volo', 'Lgt Np Tc-Taer', 'SAGUARCOST CATANIA', NULL, 'ldap', 1),
('troina.giovanni', '$2b$12$5nC.xSdDNOOGUEv0XnbweOR7o.DMXSq2HiphBmk3Oi2yTcuSj4SVq', 'GIOVANNI', 'TROINA', 'giovanni.troina@mit.gov.it', 'efv', 'Tecnici di volo', 'C.F.(CP) Tc-Aer', 'SAGUARCOST CATANIA', NULL, 'ldap', 1),
('liuzzi.nicola', '$2b$12$5nC.xSdDNOOGUEv0XnbweOR7o.DMXSq2HiphBmk3Oi2yTcuSj4SVq', 'NICOLA', 'LIUZZI', 'nicola.liuzzi@mit.gov.it', 'efv', 'Tecnici di volo', 'Sc 2^ Cl Np Tc-Taer', 'SAGUARCOST CATANIA', NULL, 'ldap', 1),
('manola.salvatore', '$2b$12$5nC.xSdDNOOGUEv0XnbweOR7o.DMXSq2HiphBmk3Oi2yTcuSj4SVq', 'SALVATORE', 'MANOLA', 'salvatore.manola@mit.gov.it', 'efv', 'Tecnici di volo', 'Lgt Np Tc-Taer', 'SAGUARCOST CATANIA', NULL, 'ldap', 1),
('padellaro.gaetano', '$2b$12$5nC.xSdDNOOGUEv0XnbweOR7o.DMXSq2HiphBmk3Oi2yTcuSj4SVq', 'Gaetano', 'PADELLARO', 'gaetano.padellaro@mit.gov.it', 'efv', 'Tecnici di volo', 'Lgt Np Taer', 'SAGUARCOST CATANIA', NULL, 'ldap', 1),
('fruciano.luigi', '$2b$12$5nC.xSdDNOOGUEv0XnbweOR7o.DMXSq2HiphBmk3Oi2yTcuSj4SVq', 'Luigi', 'FRUCIANO', 'luigi.fruciano@mit.gov.it', 'efv', 'Tecnici di volo', '2° Capo Sc Qc  Np Taer', 'SAGUARCOST CATANIA', NULL, 'ldap', 1),
('amato.andrea', '$2b$12$5nC.xSdDNOOGUEv0XnbweOR7o.DMXSq2HiphBmk3Oi2yTcuSj4SVq', 'ANDREA', 'AMATO', 'andrea.amato@mit.gov.it', 'efv', 'Tecnici di volo', 'Sc 1^ Cl Np Ms-Saer', 'SAGUARCOST CATANIA', NULL, 'ldap', 1),
('argentieri.domenico', '$2b$12$5nC.xSdDNOOGUEv0XnbweOR7o.DMXSq2HiphBmk3Oi2yTcuSj4SVq', 'DOMENICO', 'ARGENTIERI', 'domenico.argentieri@mit.gov.it', 'efv', 'Tecnici di volo', 'C° 2^ Cl Np Ms-Saer', 'SAGUARCOST CATANIA', NULL, 'ldap', 1),
('gagliano.gabriele', '$2b$12$5nC.xSdDNOOGUEv0XnbweOR7o.DMXSq2HiphBmk3Oi2yTcuSj4SVq', 'GABRIELE', 'GAGLIANO', 'gabriele.gagliano@mit.gov.it', 'efv', 'Tecnici di volo', '1° Lgt Np Ms-Saer', 'SAGUARCOST CATANIA', NULL, 'ldap', 1),
('uccheddu.simome', '$2b$12$5nC.xSdDNOOGUEv0XnbweOR7o.DMXSq2HiphBmk3Oi2yTcuSj4SVq', 'SIMOME', 'UCCHEDDU', 'simome.uccheddu@mit.gov.it', 'efv', 'Piloti', 'T.V.(CP) Pil', 'SAGUARCOST CATANIA', NULL, 'ldap', 1),
('sorrenti.sabino', '$2b$12$5nC.xSdDNOOGUEv0XnbweOR7o.DMXSq2HiphBmk3Oi2yTcuSj4SVq', 'SABINO', 'SORRENTI', 'sabino.sorrenti@mit.gov.it', 'efv', 'Piloti', 'T.V.(CP) Pil', 'SAGUARCOST CATANIA', NULL, 'ldap', 1),
('grassof..francesco', '$2b$12$5nC.xSdDNOOGUEv0XnbweOR7o.DMXSq2HiphBmk3Oi2yTcuSj4SVq', 'FRANCESCO', 'GRASSO F.', 'francesco.grassof.@mit.gov.it', 'efv', 'Tecnici di volo', 'C.F.(CP) Tc-Eli', 'SAGUARCOST CATANIA', NULL, 'ldap', 1),
('cappellacci.giorgia', '$2b$12$5nC.xSdDNOOGUEv0XnbweOR7o.DMXSq2HiphBmk3Oi2yTcuSj4SVq', 'GIORGIA', 'CAPPELLACCI', 'giorgia.cappellacci@mit.gov.it', 'efv', 'Piloti', 'T.V.(CP) Pil', 'SAGUARCOST PESCARA', NULL, 'ldap', 1),
('calo.luigi', '$2b$12$5nC.xSdDNOOGUEv0XnbweOR7o.DMXSq2HiphBmk3Oi2yTcuSj4SVq', 'LUIGI', 'CALO', 'luigi.calo@mit.gov.it', 'efv', 'Piloti', 'C.C.(CP) Pil', 'SAGUARCOST CATANIA', NULL, 'ldap', 1),
('bruschetta.gaetano', '$2b$12$5nC.xSdDNOOGUEv0XnbweOR7o.DMXSq2HiphBmk3Oi2yTcuSj4SVq', 'GAETANO', 'BRUSCHETTA', 'gaetano.bruschetta@mit.gov.it', 'efv', 'Tecnici di volo', 'Lgt Np Tc-Taer', 'SAGUARCOST CATANIA', NULL, 'ldap', 1),
('plastini.giuseppe', '$2b$12$5nC.xSdDNOOGUEv0XnbweOR7o.DMXSq2HiphBmk3Oi2yTcuSj4SVq', 'GIUSEPPE', 'PLASTINI', 'giuseppe.plastini@mit.gov.it', 'efv', 'Tecnici di volo', 'Lgt Np Tc-Taer', 'SAGUARCOST CATANIA', NULL, 'ldap', 1),
('pappalardo.gianluigi', '$2b$12$5nC.xSdDNOOGUEv0XnbweOR7o.DMXSq2HiphBmk3Oi2yTcuSj4SVq', 'GIANLUIGI', 'PAPPALARDO', 'gianluigi.pappalardo@mit.gov.it', 'efv', 'Tecnici di volo', 'Lgt Np Ms-Saer', 'SAGUARCOST CATANIA', NULL, 'ldap', 1),
('patane.nicola', '$2b$12$5nC.xSdDNOOGUEv0XnbweOR7o.DMXSq2HiphBmk3Oi2yTcuSj4SVq', 'NICOLA', 'PATANE', 'nicola.patane@mit.gov.it', 'efv', 'Operatori di volo', 'SC Np Ov', 'SAGUARCOST CATANIA', NULL, 'ldap', 1),
('picuno.zelico', '$2b$12$5nC.xSdDNOOGUEv0XnbweOR7o.DMXSq2HiphBmk3Oi2yTcuSj4SVq', 'ZELICO', 'PICUNO', 'zelico.picuno@mit.gov.it', 'efv', 'Operatori di volo', 'C°2^Cl Np Ov', 'SAGUARCOST CATANIA', NULL, 'ldap', 1),
('pace.carlo', '$2b$12$5nC.xSdDNOOGUEv0XnbweOR7o.DMXSq2HiphBmk3Oi2yTcuSj4SVq', 'CARLO', 'PACE', 'carlo.pace@mit.gov.it', 'efv', 'Operatori di volo', 'C°2^Cl Np Ov', 'SAGUARCOST CATANIA', NULL, 'ldap', 1),
('tusa.giuseppe', '$2b$12$5nC.xSdDNOOGUEv0XnbweOR7o.DMXSq2HiphBmk3Oi2yTcuSj4SVq', 'GIUSEPPE', 'TUSA', 'giuseppe.tusa@mit.gov.it', 'efv', 'Operatori di volo', 'SC Np Ov', 'SAGUARCOST CATANIA', NULL, 'ldap', 1),
('demaria.giovanni', '$2b$12$5nC.xSdDNOOGUEv0XnbweOR7o.DMXSq2HiphBmk3Oi2yTcuSj4SVq', 'GIOVANNI', 'DE MARIA', 'giovanni.demaria@mit.gov.it', 'efv', 'Operatori di volo', 'SC Np Ov', 'SAGUARCOST CATANIA', NULL, 'ldap', 1),
('attanasio.ettore', '$2b$12$5nC.xSdDNOOGUEv0XnbweOR7o.DMXSq2HiphBmk3Oi2yTcuSj4SVq', 'ETTORE', 'ATTANASIO', 'ettore.attanasio@mit.gov.it', 'efv', 'Operatori di volo', 'SC Np Ov', 'SAGUARCOST CATANIA', NULL, 'ldap', 1),
('miceli.sergio', '$2b$12$5nC.xSdDNOOGUEv0XnbweOR7o.DMXSq2HiphBmk3Oi2yTcuSj4SVq', 'SERGIO', 'MICELI', 'sergio.miceli@mit.gov.it', 'efv', 'Operatori di volo', 'C°3^Cl Np Ov', 'SAGUARCOST CATANIA', NULL, 'ldap', 1),
('guglielmino.giuseppe', '$2b$12$5nC.xSdDNOOGUEv0XnbweOR7o.DMXSq2HiphBmk3Oi2yTcuSj4SVq', 'GIUSEPPE', 'GUGLIELMINO', 'giuseppe.guglielmino@mit.gov.it', 'efv', 'Tecnici di volo', 'C.C.(CP) Tc-Eli', 'SAGUARCOST CATANIA', NULL, 'ldap', 1),
('grassoa..alfio', '$2b$12$5nC.xSdDNOOGUEv0XnbweOR7o.DMXSq2HiphBmk3Oi2yTcuSj4SVq', 'ALFIO', 'GRASSO A.', 'alfio.grassoa.@mit.gov.it', 'efv', 'Tecnici di volo', 'Sc 1^ Cl Np Ms-Saer', 'SAGUARCOST CATANIA', NULL, 'ldap', 1),
('dreon.david', '$2b$12$5nC.xSdDNOOGUEv0XnbweOR7o.DMXSq2HiphBmk3Oi2yTcuSj4SVq', 'DAVID', 'DREON', 'david.dreon@mit.gov.it', 'efv', 'Piloti', 'S.T.V.(CP) Pil', 'SAGUARCOST CATANIA', NULL, 'ldap', 1),
('salvati.davide', '$2b$12$5nC.xSdDNOOGUEv0XnbweOR7o.DMXSq2HiphBmk3Oi2yTcuSj4SVq', 'DAVIDE', 'SALVATI', 'davide.salvati@mit.gov.it', 'efv', 'Tecnici di volo', 'SC Np Ms-Saer', 'SAGUARCOST CATANIA', NULL, 'ldap', 1),
('mangio.antonino', '$2b$12$5nC.xSdDNOOGUEv0XnbweOR7o.DMXSq2HiphBmk3Oi2yTcuSj4SVq', 'ANTONINO', 'MANGIO', 'antonino.mangio@mit.gov.it', 'efv', 'Tecnici di volo', 'Lgt Np Ms-Saer', 'SAGUARCOST CATANIA', NULL, 'ldap', 1),
('calabretta.vincenzo', '$2b$12$5nC.xSdDNOOGUEv0XnbweOR7o.DMXSq2HiphBmk3Oi2yTcuSj4SVq', 'VINCENZO', 'CALABRETTA', 'vincenzo.calabretta@mit.gov.it', 'efv', 'Tecnici di volo', 'Lgt Np Tc-Eli', 'SAGUARCOST CATANIA', NULL, 'ldap', 1),
('ugenti.giancarlo', '$2b$12$5nC.xSdDNOOGUEv0XnbweOR7o.DMXSq2HiphBmk3Oi2yTcuSj4SVq', 'GIANCARLO', 'UGENTI', 'giancarlo.ugenti@mit.gov.it', 'efv', 'Tecnici di volo', '2°Capo Sc QcNp Ms-Saer', 'SAGUARCOST CATANIA', NULL, 'ldap', 1),
('massafra.cosimino', '$2b$12$5nC.xSdDNOOGUEv0XnbweOR7o.DMXSq2HiphBmk3Oi2yTcuSj4SVq', 'COSIMINO', 'MASSAFRA', 'cosimino.massafra@mit.gov.it', 'efv', 'Tecnici di volo', 'Com 1 ^ Cl Np Ms-Saer', 'SAGUARCOST CATANIA', NULL, 'ldap', 1),
('marano.sebastiano', '$2b$12$5nC.xSdDNOOGUEv0XnbweOR7o.DMXSq2HiphBmk3Oi2yTcuSj4SVq', 'Sebastiano', 'MARANO', 'sebastiano.marano@mit.gov.it', 'efv', 'Tecnici di volo', 'Sc 2^ Cl  Np Tc-Taer', 'SAGUARCOST CATANIA', NULL, 'ldap', 1),
('lucarini.flavio', '$2b$12$5nC.xSdDNOOGUEv0XnbweOR7o.DMXSq2HiphBmk3Oi2yTcuSj4SVq', 'Flavio', 'LUCARINI', 'flavio.lucarini@mit.gov.it', 'efv', 'Tecnici di volo', 'Sc 2^ Cl.Np Ms-Saer', 'SAGUARCOST CATANIA', NULL, 'ldap', 1),
('chenda.andrea', '$2b$12$5nC.xSdDNOOGUEv0XnbweOR7o.DMXSq2HiphBmk3Oi2yTcuSj4SVq', 'ANDREA', 'CHENDA', 'andrea.chenda@mit.gov.it', 'efv', 'Piloti', 'C.F. (CP) Pil', 'MARIGOCACAP', NULL, 'ldap', 1),
('d^arrigo.roberto', '$2b$12$5nC.xSdDNOOGUEv0XnbweOR7o.DMXSq2HiphBmk3Oi2yTcuSj4SVq', 'ROBERTO', 'D^ARRIGO', 'roberto.d^arrigo@mit.gov.it', 'efv', 'Tecnici di volo', 'C.F. (CP) Tc-Eli', 'SAGUARCOST PESCARA', NULL, 'ldap', 1),
('martinia..alfonso', '$2b$12$5nC.xSdDNOOGUEv0XnbweOR7o.DMXSq2HiphBmk3Oi2yTcuSj4SVq', 'ALFONSO', 'MARTINI A.', 'alfonso.martinia.@mit.gov.it', 'efv', 'Tecnici di volo', 'C° 3^Cl Np/Tc-Taer', 'SAGUARCOST CATANIA', NULL, 'ldap', 1),
('zanasi.zaira', '$2b$12$5nC.xSdDNOOGUEv0XnbweOR7o.DMXSq2HiphBmk3Oi2yTcuSj4SVq', 'ZAIRA', 'ZANASI', 'zaira.zanasi@mit.gov.it', 'efv', 'Operatori di volo', 'SC Np Ov', 'SAGUARCOST PESCARA', NULL, 'ldap', 1),
('palmese.valerio', '$2b$12$5nC.xSdDNOOGUEv0XnbweOR7o.DMXSq2HiphBmk3Oi2yTcuSj4SVq', 'VALERIO', 'PALMESE', 'valerio.palmese@mit.gov.it', 'efv', 'Tecnici di volo', 'Sc Np Ms-Saer', 'SAGUARCOST CATANIA', NULL, 'ldap', 1),
('contento.salvatore', '$2b$12$5nC.xSdDNOOGUEv0XnbweOR7o.DMXSq2HiphBmk3Oi2yTcuSj4SVq', 'SALVATORE', 'CONTENTO', 'salvatore.contento@mit.gov.it', 'efv', 'Tecnici di volo', 'Sc Np Tc-Taer', 'SAGUARCOST CATANIA', NULL, 'ldap', 1),
('devita.giovanni', '$2b$12$5nC.xSdDNOOGUEv0XnbweOR7o.DMXSq2HiphBmk3Oi2yTcuSj4SVq', 'GIOVANNI', 'DE VITA', 'giovanni.devita@mit.gov.it', 'efv', 'Tecnici di volo', 'Sc Np Tc-Taer', 'SAGUARCOST CATANIA', NULL, 'ldap', 1),
('palmiotto.michele', '$2b$12$5nC.xSdDNOOGUEv0XnbweOR7o.DMXSq2HiphBmk3Oi2yTcuSj4SVq', 'MICHELE', 'PALMIOTTO', 'michele.palmiotto@mit.gov.it', 'efv', 'Tecnici di volo', 'Sc Np Ms-Saer', 'SAGUARCOST CATANIA', NULL, 'ldap', 1),
('brunoo.marco', '$2b$12$5nC.xSdDNOOGUEv0XnbweOR7o.DMXSq2HiphBmk3Oi2yTcuSj4SVq', 'MARCO', 'BRUNOo', 'marco.brunoo@mit.gov.it', 'efv', 'Operatori di volo', 'SC Np Ov', 'SAGUARCOST CATANIA', NULL, 'ldap', 1),
('sarao.antonino', '$2b$12$5nC.xSdDNOOGUEv0XnbweOR7o.DMXSq2HiphBmk3Oi2yTcuSj4SVq', 'ANTONINO', 'SARAO', 'antonino.sarao@mit.gov.it', 'efv', 'Tecnici di volo', '1° Lgt Np Ms-Saer', 'SAGUARCOST CATANIA', NULL, 'ldap', 1),
('allegra.armando', '$2b$12$5nC.xSdDNOOGUEv0XnbweOR7o.DMXSq2HiphBmk3Oi2yTcuSj4SVq', 'ARMANDO', 'ALLEGRA', 'armando.allegra@mit.gov.it', 'efv', 'Operatori di volo', 'SC Np Ov', 'SAGUARCOST CATANIA', NULL, 'ldap', 1),
('allegracl.claudio', '$2b$12$5nC.xSdDNOOGUEv0XnbweOR7o.DMXSq2HiphBmk3Oi2yTcuSj4SVq', 'CLAUDIO', 'ALLEGRAcl', 'claudio.allegracl@mit.gov.it', 'efv', 'Operatori di volo', '2° Capo Np Ov', 'SAGUARCOST CATANIA', NULL, 'ldap', 1),
('arena.antonino', '$2b$12$5nC.xSdDNOOGUEv0XnbweOR7o.DMXSq2HiphBmk3Oi2yTcuSj4SVq', 'ANTONINO', 'ARENA', 'antonino.arena@mit.gov.it', 'efv', 'Tecnici di volo', '2°Capo Aiutante Np ETE-Taer', 'SAGUARCOST PESCARA', NULL, 'ldap', 1),
('melone.benito', '$2b$12$5nC.xSdDNOOGUEv0XnbweOR7o.DMXSq2HiphBmk3Oi2yTcuSj4SVq', 'BENITO', 'MELONE', 'benito.melone@mit.gov.it', 'efv', 'Operatori di volo', 'Com Np Ov', 'SAGUARCOST PESCARA', NULL, 'ldap', 1),
('camerlengo.giovanni', '$2b$12$5nC.xSdDNOOGUEv0XnbweOR7o.DMXSq2HiphBmk3Oi2yTcuSj4SVq', 'GIOVANNI', 'CAMERLENGO', 'giovanni.camerlengo@mit.gov.it', 'efv', 'Piloti', 'G.M.(CP) Pil', 'SAGUARCOST CATANIA', NULL, 'ldap', 1),
('renzetti.stefano', '$2b$12$5nC.xSdDNOOGUEv0XnbweOR7o.DMXSq2HiphBmk3Oi2yTcuSj4SVq', 'STEFANO', 'RENZETTI', 'stefano.renzetti@mit.gov.it', 'efv', 'Tecnici di volo', 'Sc  Aiutante Np Tc- Taer', 'SAGUARCOST PESCARA', NULL, 'ldap', 1),
('bottaro.alessandro', '$2b$12$5nC.xSdDNOOGUEv0XnbweOR7o.DMXSq2HiphBmk3Oi2yTcuSj4SVq', 'ALESSANDRO', 'BOTTARO', 'alessandro.bottaro@mit.gov.it', 'efv', 'Operatori di volo', 'SC Np Ov', 'SAGUARCOST CATANIA', NULL, 'ldap', 1),
('russo.benedetto', '$2b$12$5nC.xSdDNOOGUEv0XnbweOR7o.DMXSq2HiphBmk3Oi2yTcuSj4SVq', 'BENEDETTO', 'RUSSO', 'benedetto.russo@mit.gov.it', 'efv', 'Operatori di volo', 'SC Np Ov', 'SAGUARCOST CATANIA', NULL, 'ldap', 1),
('dibiase.salvatore', '$2b$12$5nC.xSdDNOOGUEv0XnbweOR7o.DMXSq2HiphBmk3Oi2yTcuSj4SVq', 'SALVATORE', 'DI BIASE', 'salvatore.dibiase@mit.gov.it', 'efv', 'Operatori di volo', 'SC Np Ov', 'SAGUARCOST CATANIA', NULL, 'ldap', 1),
('borriello.daniel', '$2b$12$5nC.xSdDNOOGUEv0XnbweOR7o.DMXSq2HiphBmk3Oi2yTcuSj4SVq', 'DANIEL', 'BORRIELLO', 'daniel.borriello@mit.gov.it', 'efv', 'Piloti', 'G.M.(CP) Pil', 'SAGUARCOST PESCARA', NULL, 'ldap', 1),
('caricola.saverio', '$2b$12$5nC.xSdDNOOGUEv0XnbweOR7o.DMXSq2HiphBmk3Oi2yTcuSj4SVq', 'SAVERIO', 'CARICOLA', 'saverio.caricola@mit.gov.it', 'efv', 'Operatori di volo', 'SC Np Ov', 'SAGUARCOST PESCARA', NULL, 'ldap', 1),
('tirelli.pasquale', '$2b$12$5nC.xSdDNOOGUEv0XnbweOR7o.DMXSq2HiphBmk3Oi2yTcuSj4SVq', 'PASQUALE', 'TIRELLI', 'pasquale.tirelli@mit.gov.it', 'efv', 'Operatori di volo', 'SC Np Ov', 'SAGUARCOST CATANIA', NULL, 'ldap', 1)
ON DUPLICATE KEY UPDATE
    nome              = VALUES(nome),
    cognome           = VALUES(cognome),
    email             = VALUES(email),
    categoria         = VALUES(categoria),
    grado             = VALUES(grado),
    sede_assegnazione = VALUES(sede_assegnazione),
    matricola         = VALUES(matricola),
    auth_type         = VALUES(auth_type);

-- Verifica
SELECT COUNT(*) AS totale_utenti FROM utenti;
